### ISSUE TITLE
cmake related issue on getting/referring header files path of module IotShadow-cpp 

### ISSUE THREAD

**Issue by atanubanik** [awslabs/aws-iot-device-sdk-cpp-v2#17]
I am encountering errors while trying to build a new executable using cmake with the file "aws-iot-device-sdk-cpp-v2/samples/shadow/shadow_sync/main.cpp". 

As prerequisite, I’ve downloaded aws-crt-cpp & aws-iot-device-sdk-cpp-v2 from git, built the libraries using CMake & make (gcc 7.3) in a different folder (e.g. ~/temp/bin)

I’ve copied the CMakeLists.txt (from shadow_sync) and modified to build my project. 

It links with IotShadow-cpp, so I’ve used the below line to load the package.  
	find_package(IotShadow-cpp REQUIRED)

To find the package I’d to add the below lines
	list(APPEND CMAKE_MODULE_PATH "${CMAKE_INSTALL_PREFIX}/lib/IotShadow-cpp/cmake")
	list(APPEND CMAKE_MODULE_PATH "${CMAKE_INSTALL_PREFIX}/lib/cmake")

I had to rename the file to lower case (iotshadow-cpp-config.cmake) and I figured this out after trying several things!

Now, the package is loaded but include directories are not, causing compilation to fail.

Please advise if I’m missing anything or there is any issue elsewhere. I’m attaching the below files for your review.

**Attachments:**
[New CMakeLists.txt](https://github.com/awslabs/aws-iot-device-sdk-cpp-v2/files/2991073/CMakeLists.txt)
[main.cpp](https://github.com/awslabs/aws-iot-device-sdk-cpp-v2/blob/master/samples/shadow/shadow_sync/main.cpp)
[Original CMakeLists.txt](https://github.com/awslabs/aws-iot-device-sdk-cpp-v2/blob/master/samples/shadow/shadow_sync/CMakeLists.txt)

**Comment by bretambrose** [comment]
Rather than trying to mess with paths in a CMakeLists.txt, have you tried doing an install of the libraries you're depending on?  If you're not comfortable installing to the system, you can also install to a local directory under you're control.

The general steps look like:

1. Build the libaries with CMAKE_INSTALL_PREFIX set to where you want them to go (or leave blank for a system level install, but I wouldn't recommend that for an in-preview sdk yet)
1. make install the libraries
1. Build your app with CMAKE_PREFIX_PATH set to the install directory

**Comment by Kiddinglife** [comment]
If you include imported lib all include files are automatically added.
