### ISSUE TITLE
Sample code changed and no docs available 

### ISSUE THREAD

**Issue by ravichandhraRean** [awslabs/aws-iot-device-sdk-cpp-v2#24]
Hi @JonathanHenson ,

I saw in this commit the shadow_sync sample code changed https://github.com/awslabs/aws-iot-device-sdk-cpp-v2/commit/ba362fc59e7b6b55b04f3aa86e0105e3b2a90b38#diff-5d22053c1c1868335bd4609cad0c6da9 

can we still use the old sample code or how to use this sdk there no docs available so we are confused to whether use the old sample code or this new one.

Thank you.

Regards,
Ravichandhra Palla,
Hitachi Vantara.

**Comment by justinboswell** [comment]
Those changes were due to required lifetime/API changes in the lower level libraries (specifically around the HostResolver). If you update to the latest version of this SDK, you will need to make the same changes to your app, which should just mean creating a HostResolver and handing it to the ClientBootstrap, and then using the MqttClientConnectionConfigBuilder to simplify connection creation. You could instead create your own options, but it will be a more manual process.

**Comment by amitguptaRean** [comment]
**### I tried this change. It crashes for my greengrass setup.**
Aws::Iot::MqttClient* mqttClient;

May 21 22:11:49 D16 device_agent[6628]: [22:11:49:897976690: +00:00] [---E---] [thread 6631] Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed
May 21 22:11:49 D16 device_agent[6628]: Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed'


So I reverted to the previous Mqtt client
Mqtt::MqttClient* mqttClient;`

Why do we have 2 different MqttClient classes ?

**Comment by justinboswell** [comment]
There's only 1 MqttClient class. There's just also a connection builder class now, to simplify connection creation.

**Comment by justinboswell** [comment]
Closing as this should have been resolved offline. If there are further questions, feel free to re-open this ticket.
