### ISSUE TITLE
IoT Core - SDK never sends OnResume() callback if mqtt keep alive interval expires

### ISSUE THREAD

**Issue by amitguptaRean** [awslabs/aws-iot-device-sdk-cpp-v2#29]
**We tested the SDK for IoT Core (not Greengrass).**

1) We created an MQTT connection
2) Removed the ethernet cable on device and waited till we got the the $aws/events/presence/disconnected/D17 on AWS IoT core console
3) Plugged the ethernet cable back
4) mqtt connection callback OnResume() never got called back. Connection state remains 1 (Connecting) forever.

**Comment by graebm** [comment]
Do you see this same behavior if you run this same test on the "mqtt_pub_sub" sample? If you run this sample and just do nothing, it will stay connected to the IoT server, and will print messages about any change to connection state (connected, interrupted, resumed, disconnected). It's built along with  `aws-crt-cpp`. You can run it like so:

`./aws-crt-cpp-build/samples/mqtt_pub_sub/aws-crt-cpp-mqtt-pub-sub --endpoint {my-endpoint}.iot.{region}.amazonaws.com --ca_file {path-to-root-ca} --cert {path-to-cert} --key {path-to-key} --topic samples/test`

**Comment by amitguptaRean** [comment]
Past 2 days I an trying to build AWS SDK , and has failed. As soon as I am able to build this, I will post response.

**Comment by graebm** [comment]
Have you updated aws-crt-cpp to [v0.4.0](https://github.com/awslabs/aws-crt-cpp/releases/tag/v0.4.0)?

**Comment by amitguptaRean** [comment]
Yes we took latest of everything including crt

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by graebm** [comment]
What OS / build system / compiler are you using?

**Comment by amitguptaRean** [comment]
We are on Debian linux, using latest gcc
Please note we have been building AWS iot sdk cpp v2 all this time, until this change in aws_crt done recently. Did you get a chance to look at issue #35 ?

**Comment by graebm** [comment]
I'm putting together continuous integration for this repository right now so we can be sure that it's working across many configurations. It's going to take a while to get this done...

Have you tried obliterating the aws-crt-cpp and its build directory and cloning it all again from scratch? From the errors you're sharing, it really looks like aws-crt-cpp isn't pulling all the latest versions of its dependencies.

**Comment by graebm** [comment]
I have a PR that adds continuous integration for multiple platforms: https://github.com/awslabs/aws-iot-device-sdk-cpp-v2/pull/36
I can confirm that what's currently in master ought to build fine on Linux.

I've also confirmed that `aws-crt-cpp` has issues rebuilding when an existing installation is updated in place. Delete your `aws-crt-cpp-build` directory and rebuild and you ought to be fine. I added a task to our backlog to address this rebuild issue.

**Comment by amitguptaRean** [comment]
**We tried to the sample program against GG core, it fails.**
Connecting...
Segmentation fault

./aws-crt-cpp-mqtt-pub-sub --endpoint api-amit.5gdcs.com --ca_file /home/agupta/AmazonRootCA1.pem --cert /home/agupta/6c261062ab-certificate.pem.crt --key /home/agupta/6c261062ab-private.pem.key --topic samples/test

Please add port 8883 support to sample so as we can run this for GG and send you the report if we observe same behavior in your sample program.

**Next we are were able to run to against IoT core**
./aws-crt-cpp-mqtt-pub-sub --endpoint a479q5rfhr1ub-ats.iot.us-east-1.amazonaws.com --ca_file /home/agupta/AmazonRootCA1.pem --cert /home/agupta/6c261062ab-certificate.pem.crt --key /home/agupta/6c261062ab-private.pem.key --topic samples/test

I see aws lifecycle events.
But when I try to disconnect my wire, i loose my putty session, and the program is no longer alive to tell me if it resumes ...

**Comment by ravichandhraRean** [comment]
Hi @graebm and @JonathanHenson ,

Thank you for supporting us.

As pointed by @graebm I tested the mqtt_pub_sub sample and able to reproduce the same behavior

**Note: these sample programs are not able to test with greengrass (as mentioned by @amitguptaRean ) that is another issue**

**Test explanation:**
Test setup:
1. as @amitguptaRean mentioned he is facing some issues to test with it by removing the network cable, to prevent those i did this.
2. Connected my Pi device to a monitor with keyboard and mouse, and Pi connected to WiFi, so When I disconnected/turn-off my wifi for testing purpose still I can see how the program is behaving.

Procedure/Steps followed:
1. started the pub_sub sample with all needed arguments and the program is able to connect to IoT core(it published a connected message on Life-cycle topic).
2. We entered some messages, the program able to publish those messages to given IoT topic. We published some messages on that topic from IoT test console, the program able to receive those messages.
3. Turned off the Wifi connection on my Pi device and waited to see the OnInterruoted message(but it never happened)
4. After some time(around after 270 seconds - I assuming this is keep-alive expiration) a disconnected message published to Life-cycle topic, but no OnInterrupted/or any other message displayed in program(program still running)
5. After this I turned on Wifi on Pi device, but no OnResume happened / no connection re-established
6. After this program is still running but not receiving any messages published from IoT test console, when we give message to publish it is saying successfully published but no message is coming to the IoT topic.

Strange Behavior:
1. when there is no connection also if we give some message to program it is saying published successfully but no message coming to IoT test console topic.

Scenario-2:
1. instead of waiting for some long time(5 minutes / more than that) I turned on WiFi after 20-30 seconds
2. then also I couldn't see any OnInterrupted , OnResume callbacks happening
3. But this the disconnect message not published to IoT life-cycle topic and after WiFi turned on the publish working.

We are really blocked to deliver our customer project because these major/critical SDK bugs, please look into this. We are ready to demonstrate these bugs in zoom call/some other channel if needed.

Thank you,

Regards,
Ravichandhra Palla.

**Comment by ravichandhraRean** [comment]
The current SDK Mqtt connection behavior really confusing us,

as you mentioned it will only call OnDisconnected when someone make a call to Disconnect() method, as per this we are expecting/assuming the below behavior in SDK mqtt connection,

1. It will create a mqtt connection and do the internall pings to keep the connection alive
2. When any-type(network loss/disturbance) of network/other issues happened/caused it will call OnInterrupt callback
3. When the network and connection back then it will call OnResume callback
4. When OnInterrupt happened either it will queue up the messages or it will fail to complete that operation
5. It will never disonnects the connection(may be here I am wrong why because when there is a no network for long time how can it keep the connection) or it will reestablish the connection OnResume callback
6. Either it should re-establish the connection if there is no , or it should notify us so that we can re-create the connection (it is not doing any)

There are other queries also regarding how the SDK supports the persistent session feature providing by IoT service from AWS but I will not ask them as of now, after clearing all these critical issues I will post them.

Looking for resolutions.

Thank you.

Regards,
Ravichandhra Palla.

**Comment by ravichandhraRean** [comment]
Hi @graebm / @JonathanHenson ,

Any update on this.

Thank you.
