### ISSUE TITLE
MQTT Connection deadlock if any invalid details provided

### ISSUE THREAD

**Issue by ravichandhraRean** [awslabs/aws-iot-device-sdk-cpp-v2#50]
Hi Team,

@JonathanHenson 
@justinboswell 

When we provide any invalid/incorrect connection details, we are observing an hang/deadlock in sdk (no connection callback receiving)

**Case-I:**
//invalid certificates
	MqttCertificate cert1; 
	cert1.HostAddress = host_address; // **used a valid IoT Core endpoint**
	cert1.port = port; **// used 443**
	cert1.rootCA = "na";
	cert1.clientCRT = "na";
	cert1.clientKey = "na";

**Result for Case-I:** 
1. hang/deadlock in sdk and no callback receiving from sdk

**Case-II:**
//invalid endpoint
	MqttCertificate cert1;
	cert1.HostAddress = "172.16.2.109"; **// this is not a valid endpoint** 
	cert1.port = port; **// used 443**
	cert1.rootCA = cert_root + root_ca;
	cert1.clientCRT = cert_root + device_cert;
	cert1.clientKey = cert_root + device_key;

**Result for Case-II:**
1. Strangely here MQTT Connection was successful
2. But when we used that connection to create subscriptions no callback received and hang/deadlock observing in sdk

Please test these from your side also and provide us fix.

Thank you.

Regards,
Ravichandhra Palla,
Hitachi Vantara.

**Comment by graebm** [comment]
We've investigated what went wrong here and have a batch of changes in the works to address it. Here's what's going on:

1) The TLS context builder wasn't exposing any errors that happened along the way (in this case, the certificates didn't load).
2) This led to a TLS connection being established on port 443, but without any certificates, which led to the server thinking that we wanted to establish over websockets, instead of directly over MQTT.
3) The client still expected to communicate over MQTT so sent the CONNECT packet
4) The server (expected a websocket upgrade request over HTTPS) did not respond to the MQTT CONNECT packet
5) The client hangs forever waiting for CONNACK

**Comment by ravichandhraRean** [comment]
Understood, Thank you @graebm .

We are waiting for the fixes.

-Ravi

**Comment by graebm** [comment]
FIxed in latest.
Note the minor changes to the samples. If the configuration turns out invalid, check `clientConfig.LastError()` to find out why instead of the global `LastError()`function.

**Comment by ravichandhraRean** [comment]
We will test this, thank you @graebm
